### ISSUE TITLE
Embed question

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/saas-website#1]
Hi @thomasjbradley!
I see that we are required to have embed and embed containers as part of this assignment, but the way we have done my images in CSS, it doesn't seem that I will be able to do this?
Do you have any suggestions? :)
Thanks!
Christine

**Comment by thomasjbradley** [comment]
What about using an embed container for the large microscope image on the homepage?

**Comment by cmvolden** [comment]
Oh sorry I forgot to mention.. I planned on using that one for the index,
but it requires for all pages. Should I just add some photos in?

**Comment by thomasjbradley** [comment]
Would it be very difficult to add more photos?

**Comment by cmvolden** [comment]
I don’t think so, it’s a medical website so I could probably add a
“presentation” style photo to each page above the footer, or a promo photo
stating there is a one month free trial, etc.
